### ISSUE TITLE
Crash attempting to open/play a local file

### ISSUE THREAD

**Issue by markarupert** [moust/cordova-plugin-videoplayer#74]
I am recording a video with the camera then attempting to play it back. When I do the app crashes. Details below.

--------- beginning of crash
07-07 17:32:08.394  9915  9915 E AndroidRuntime: FATAL EXCEPTION: main
07-07 17:32:08.394  9915  9915 E AndroidRuntime: Process: com.geospacelabs.recoll, PID: 9915
07-07 17:32:08.394  9915  9915 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowInsetsController com.android.internal.policy.DecorView.getWindowInsetsController()' on a null object reference
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.getInsetsController(PhoneWindow.java:4120)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.moust.cordova.videoplayer.VideoPlayer.openVideoDialog(VideoPlayer.java:124)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.moust.cordova.videoplayer.VideoPlayer.lambda$execute$0$VideoPlayer(VideoPlayer.java:73)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.moust.cordova.videoplayer.-$$Lambda$VideoPlayer$6iPzOqaF3UHMLVT7mZWDhTUZOho.run(Unknown Source:6)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-07 17:32:08.394  9915  9915 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
07-07 17:32:08.400  1111 10598 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-07 17:32:08.400  1111  1915 D Debug   : low && ship && 3rdparty app crash, do not dump
07-07 17:32:08.400  1111  1915 W ActivityManager: crash : com.geospacelabs.recoll,10614
07-07 17:32:08.401  1111  1915 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1162 com.android.server.am.AppErrors.crashApplicationInner:579 com.android.server.am.AppErrors.crashApplication:443 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:12323 com.android.server.am.ActivityManagerService.handleApplicationCrash:12258 
07-07 17:32:08.401  1111  1915 W ActivityTaskManager:   Force finishing activity com.geospacelabs.recoll/.MainActivity
07-07 17:32:08.401  1111  1915 V WindowManager: Prepare app transition: transit=TRANSIT_CRASHING_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_UNSET alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:5804 com.android.server.wm.DisplayContent.prepareAppTransition:5798 com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked:2733 com.android.server.wm.RootWindowContainer.finishTopCrashedActivities:2641 com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities:8886 
07-07 17:32:08.402  1111  1915 D InputDispatcher: Focused application set to (0): ee93e20
07-07 17:32:08.403  1111  1915 V WindowManager: Changing focus from Window{8c960e u0 com.geospacelabs.recoll/com.geospacelabs.recoll.MainActivity} to null displayId=0

**Comment by godsgracetech** [comment]
Hi @markarupert 
We are also getting the same issue, it is crashing app if we try to play the video. We have been researching for solution since last two days, but no luck. Did you find any solution for this problem ?

Appreciate if any suggestions
Thank you very much

**Comment by aecheb** [comment]
Hi everyone, I have the same problem. Did you find a solution yet?
